### ISSUE TITLE
Vesc based hardware support

### ISSUE THREAD

**Issue by charclo** [teslabs/spinner#2]
Hello, 

How difficult would it be to add stm32f405 support? I have VESC-based hardware that I would like to use with this software. I have experience coding embedded C but no experience with zephyr yet, so don't know if this would be a lot of work.
Same question for phase current sampling support?

My goal would be to run my inverter at 100 kHz PWM (real, not Zero vector frequency) rate. My hardware has GaN transistors and I need a higher switching frequency to make full use of these, to make my measurements.

Greetings,

Michaël

**Comment by gmarull** [comment]
stm32f405 is a supported SoC in Zephyr, so it should be fairly trivial. Just add support for F4 in spinner drivers and a new board would be enough.

**Comment by charclo** [comment]
Thanks for the quick answer. 

Would the code have to change a lot for using in-line current sensing instead of low-side current sensing?  I wouldn't have to synchronize the adc acquisition any more to the middle of the PWM period. Anything else?

**Comment by gmarull** [comment]
> Thanks for the quick answer.
> 
> Would the code have to change a lot for using in-line current sensing instead of low-side current sensing? I wouldn't have to synchronize the adc acquisition any more to the middle of the PWM period. Anything else?

Code will need a bit of adjustment, since e.g. de svpwm driver configures CH4 to trigger ADC measurement. This also provides effectively the regulation timing, so you'll need to adjust that part as well.

**Comment by charclo** [comment]
Thanks, I’ll give it a try and if I succeed make a pull request.

**Comment by charclo** [comment]
I installed zephyr and the SDK and tried to build your project but I'm getting build errors:
(.venv) michael@ace spinner %  west build -b nucleof302r8_ihm07m1 spinner
-- west build: generating a build system
CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as

    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in CMakeLists.txt:
  cmake_minimum_required() should be called prior to this top-level project()
  call.  Please see the cmake-commands(7) manual for usage documentation of
  both commands.
This warning is for project developers.  Use -Wno-dev to suppress it.

**CMake Error at drivers/CMakeLists.txt:4 (add_subdirectory_ifdef):
  Unknown CMake command "add_subdirectory_ifdef".**


CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.26)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!
FATAL ERROR: command exited with status 1: /opt/homebrew/bin/cmake -DWEST_PYTHON=/Users/michael/zephyrproject/.venv/bin/python3.11 -B/Users/michael/Projects/spinner/build -GNinja -DBOARD=nucleof302r8_ihm07m1 -S/Users/michael/Projects/spinner/spinner

Any idea what is causing this?

I tried building an uploading a sample (blinky) to my board and it worked fine, so I think my build system should be fine. Google isn't giving me any answers to what it could be.
